### ISSUE TITLE
Monlog v2 support

### ISSUE THREAD

**Issue by gwharton** [noxdk/monolog-journal-handler#1]
Is there any reason why this shouldn't work with monolog v2?

I'd like to use this module with Magento, but they're still locked to v2.7

**Comment by noxdk** [comment]
I chose to support v3 only for maintainability. Also, I use some PHP features that are not supported on some v2 installations (like the use of `enum`) due to old PHP versions. The biggest change from v2 to v3 is the use of the `LogRecord` object instead of array, so I will have to maintain both old and new data models, and most likely drop some of the newer PHP features. 

I am not saying that it should not support v2. But right now I don't have time to develop and test v2 support. However, feel free to create a PR with this functionality.

**Comment by gwharton** [comment]
That's fine. Don't worry. It has clearly been considered. Hopefully Magento will update to V3 soon. I'll close this. Just raised on the off chance that it was compatible. But just not present in composer json.
